import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { Lang, langs } from '@/i18n'

const InterFont = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  alternates: {
    canonical: '/',
    languages: {
      en: '/en',
      fr: '/fr',
    },
  },
}

export async function generateStaticParams() {
  return langs.map(lang => ({ lang }))
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ lang: Lang }>
}>) {
  return (
    <html lang={(await params).lang}>
      <body className={InterFont.className}>{children}</body>
    </html>
  )
}
